### ISSUE TITLE
Velocity Url Comparison

### ISSUE THREAD

**Issue by Jake-Moore** [LoneDev6/BungeePackFix#22]
In `ServerResourcePackSendListener.java` when comparing pack urls after the ==, the logic there will not work if you follow the wiki (tested and fixed myself). 

(The wiki says sub servers should use external host and the link without the # or part after it.)

The self-host server URL (`serverPack`) will return as `http://host:port/pack.zip` while the new sub-server pack (`playerPack`) using that same URL, will send a pack with a hash like `http://host:port/pack.zip#...`

I suggest you parse out the `#...` hash part, or simply use `(playerPack.getUrl().startsWith(serverPack.getUrl())` which will also work.

**Comment by Jake-Moore** [comment]
Edit: if you make this change to parse and ignore the # part, it will work. I've tested that locally after pulling the code and fixing it. (Sorry I couldn't make an easy pull-request, I'm not familiar with doing that)

In other words you can change the spigot page to remove the (untested) part :)

**Comment by LoneDev6** [comment]
I didn't code the velocity part..
@YoSoyVillaa please actually test the plugin before releasing it, it's the second game breaking bug reported.

**Comment by LoneDev6** [comment]
> I suggest you parse out the `#...` hash part, or simply use `(playerPack.getUrl().startsWith(serverPack.getUrl())` which will also work.

No, it won't be reliable since the hash part is important. The pack url might stay the same but the hash change after you run /iazip to add content.

**Comment by YoSoyVillaa** [comment]
I think there is something I'm not understanding. As you say if I set the resourcepack hosting as ``self-host``, it doesn't work because Velocity says that the resourcepack that the player has applied doesn't contain the _hash_ part after the ``#``.

I've been doing some tests and having the resourcepack as ``self-host`` it saves the whole URL, including the _hash_ part.

[Prove](https://i.imgur.com/IwU5BVE.png)

When you run ``/iazip`` the zip _hash_ changes as of changing the pack content so obviously you need to reapply the texture pack, so in that case, Velocity recognises the new hash and change your texture pack.

[/iazip](https://i.imgur.com/XLhTgHA.png) - [Connection after /iazip](https://i.imgur.com/ZxhKqec.png)

In case I'm doing something wrong in the ItemsAdder config, just tell me, I don't use ItemsAdder, just a friend needed the compatibility and I wanted to contribute to the project as it is open source.

[My ItemsAdder config](https://i.imgur.com/GF5TDqv.png)

**Comment by YoSoyVillaa** [comment]
> I didn't code the velocity part.. @YoSoyVillaa please actually test the plugin before releasing it, it's the second game breaking bug reported.

In reponse to this, every change I made to the plugin I test it, the last issue was a _miss-click_ which any developer could have, and this issue I a bit strange because in my tests, it works correctly as espected.

**Comment by Jake-Moore** [comment]
Apologies for the confusion.

The java code compares java objects with == but then if that fails also accepts a bunch of combined .equals checks of the data in the packet (url, hash, etc)

I believe the confusion comes from the wiki.

On the wiki it states you must remove the hash part from the url. Doing so will break the string comparison and result in the pack being loaded every time.

![image](https://user-images.githubusercontent.com/38172916/211636723-f97cede9-26b3-4c44-9d62-38240bb3902c.jpeg)

![image](https://user-images.githubusercontent.com/38172916/211636746-73f31ca4-0956-4db9-8427-cbb848eae92a.jpeg)

**Comment by YoSoyVillaa** [comment]
No problem, thanks anyway. 

I think you could remove the ``(untested)`` tag of velocity support from the spigot page description @LoneDev6

**Comment by Jake-Moore** [comment]
And correct me if I'm wrong, but comparing the hash works great if you are on the self-host server, as it will reload it.

However iazip on the self-host server won't trigger a pack update for players on all the other subservers until they move servers and then each server they go to needs the url changed in the config.

It's great to compare hashes but i think it's a bit impractical to change the url on every other server using the remote resource pack, every time you zip it or change it.

Which I why I believe the wiki says to ignore hash, and only checks where the pack came from, the core url.

That way you don't have to edit the url with the proper hash each time.

**Comment by Jake-Moore** [comment]
I did not look at how bungee compares the packs, if they check full hash then it's fine but I don't think they do with the way the wiki is worded.

**Comment by Jake-Moore** [comment]
> I think you could remove the ``(untested)`` tag of velocity support from the spigot page description @LoneDev6 

Not yet, if you follow the wiki with velocity this plugin will not work. As your link won't have the hash part and it will be a false comparison every time.

**Comment by YoSoyVillaa** [comment]
> I did not look at how bungee compares the packs, if they check full hash then it's fine but I don't think they do with the way the wiki is worded.

The if statement that compares both pack is the same in both platforms.



> > I think you could remove the `(untested)` tag of velocity support from the spigot page description @LoneDev6
> 
> Not yet, if you follow the wiki with velocity this plugin will not work. As your link won't have the hash part and it will be a false comparison every time.

Replying to this, as both comparision are the same, I don't know how could work for Bungee and not for Velocity

**Comment by YoSoyVillaa** [comment]
Ok, I undertand you now, sorry for my misunderstanding. I think that problem is more related to ItemsAdder itselfs and the BungeePackFix behaviour, so @LoneDev6 should see what we can do and choose on of the options you told about.

If he decide to follows the wiki's logic, I will implement it on the Velocity part ASAP.

**Comment by LoneDev6** [comment]
I don't understand the need to complicate things, the Velocity code should use the same logic as my Bungeecord code.
No need to overthink about it.
Just make sure that it's the same logic and you're good to go.

**Comment by YoSoyVillaa** [comment]
I think you're not completly understanding the issue here. The Velocity code that checks the packs equality are the same. You can check it here for [bungeecord](https://github.com/LoneDev6/BungeePackFix/blob/4187e412686b018ed5713cd71d7a4a99ab613dd3/src/main/java/dev/lone/bungeepackfix/bungee/libs/packetlistener/packets/RespackSendPacketOut.java#L156) and here for [velocity](https://github.com/LoneDev6/BungeePackFix/blob/4187e412686b018ed5713cd71d7a4a99ab613dd3/src/main/java/dev/lone/bungeepackfix/velocity/listeners/ServerResourcePackSendListener.java#L41).

The problem here is in a specific case, @Jake-Moore is using the same pack for more than 1 server. If you follow the wiki to [use the same pack in more servers](https://itemsadder.devs.beer/faq/single-resourcepack-bungeecord), it tells you that in the main server the resourcepack URL would be ``https://host:port/pack.zip#packhash`` and in the other servers _(called here subservers)_, you must use ``external_host`` and in the URL put the URL of the main server texture pack **WITHOUT** the part after the `#`. 

So, if you connect to the main server, your pack URL could be ``https://host:port/pack.zip#G5LY50XBX648E73OWUP4`` (for example), and when yo connect to the second server, the proxy will receive only ``https://host:port/pack.zip``, as you remove the _hash_ part from the URL in the second server resource hosting settings, so the plugin will send you a _"new"_ resourcepack as it checks that both packs aren't the same because of different URLs.

The problem is not with the Velocity code, in Bungeecord shouldn't work too, because is an ItemsAdder issue, either with the wiki part, and remove the message which tells you to remove that part, or change the plugin (BungeePackFix) behaviour, __not the Velocity part, both parts as both doesn't work or doesn't follow the wiki's logic__. 

Nobody is complicating things, just you are not understunding the issue as it is. Thats what @Jake-Moore and I tried to explain in the last messages.

**Comment by YoSoyVillaa** [comment]
> I don't understand the need to complicate things, the Velocity code should use the same logic as my Bungeecord code. No need to overthink about it. Just make sure that it's the same logic and you're good to go.
> 
> https://github.com/LoneDev6/BungeePackFix/blob/4187e412686b018ed5713cd71d7a4a99ab613dd3/src/main/java/dev/lone/bungeepackfix/bungee/libs/packetlistener/packets/RespackSendPacketOut.java#L174
> 
> https://github.com/LoneDev6/BungeePackFix/blob/4187e412686b018ed5713cd71d7a4a99ab613dd3/src/main/java/dev/lone/bungeepackfix/bungee/libs/packetlistener/packets/RespackSendPacketOut.java#L191

The `hashCode` part has nothing to do here, what we mean by `hash` is the **part after the # in the texturepack URL**.

**Comment by LoneDev6** [comment]
Strange no one ever reported that, the plugin was online since 2021.

Anyway I'm sure the current logic is correct.
ItemsAdder puts the # hash after the URL to handle some stupid Minecraft clients ignoring the actual hash field.
So the complete URL check is mandatory in the check, do not remove anything after # .

@Jake-Moore Try to copy the url from the base server and include the # part, do not strip it out.
Let me know

**Comment by Jake-Moore** [comment]
`Furthermore, the plugin is meant to allow you to configure the same pack on several servers, its implied that if you join a subserver, if the URL of the pack shares the same base as the self-host URL, then it came from there, the hash is irrelevant at that point, it only makes it harder to update the pack across all servers. ` (from above)


I do believe that if you copy the full url with hash and set it as the remote url, it will work.

At this point I believe this is now a feature request because of the description above. 

I recently found the Boolean in bungeepackfix that specifies if the hashes should be compared.

At this point I would just say that if the hash comparing Boolean is false, the bungeepackfix should strip the has from the urls before  comparing them.

@YoSoyVillaa if you agree with this change then I believe everything is fine.

It still won't fix the wiki saying to remove the hash part, but that's for others to struggle with if LoneDev won't acknowledge that issue.

**Comment by YoSoyVillaa** [comment]
> `Furthermore, the plugin is meant to allow you to configure the same pack on several servers, its implied that if you join a subserver, if the URL of the pack shares the same base as the self-host URL, then it came from there, the hash is irrelevant at that point, it only makes it harder to update the pack across all servers. ` (from above)
> 
> 
> I do believe that if you copy the full url with hash and set it as the remote url, it will work.
> **however, this only makes things harder as every time you zip on the self-host server, you have to edit the remote host urls everywhere**
> 
> At this point I believe this is now a feature request because of the description above. 
> 
> I recently found the Boolean in bungeepackfix that specifies if the hashes should be compared.
> 
> ```toml
> 
> [equal_pack_attributes]
> hash = true
> ```
> 
> At this point I would just say that if the hash comparing Boolean is false, the bungeepackfix should strip the hash from the urls before  comparing them.
> 
> @YoSoyVillaa if you agree with this, please make the change and then everything is resolved.
> 
> It still won't fix the wiki saying to remove the hash part, but that's for others to struggle with if LoneDev won't acknowledge that issue.

That hash doesn't correspond to the URL part, it correspond to the object hash, the resource pack hash, which is a part of the packet or the file, here there are two meanings to hash, the URL part, which is your issue, and the packet hash, which is what the plugin checks if you enable that feature in config

**Comment by Jake-Moore** [comment]
I would venture a guess that on bungee, the pack url method already strips the hash, or everyone has always just kept the `hash: true` config option

**Comment by LoneDev6** [comment]
The only downside of this idea is that if you run /iazip people won't get the new pack updated since the URL is the same.

I don't really recall but I think ItemsAdder always sets the hash to encoded string `null` in order to fix this: https://bugs.mojang.com/browse/MC-164316

**Comment by Jake-Moore** [comment]
> The only downside of this idea is that if you run /iazip people won't get the new pack updated since the URL is the same, they will have to rejoin.
> 
> 
> 
> I don't really recall but I think ItemsAdder always sets the hash to encoded string `null` in order to fix this: https://bugs.mojang.com/browse/MC-164316

You are correct... 

And yes that is an issue, but not if you use .startsWith as I'm currently doing in my test fork

If you are on the same server, zipping changes the hash and it will re-apply since the startsWith returns false

(To summarize, don't edit the urls, but rather than .equals, use old.startsWith(new))

**Comment by YoSoyVillaa** [comment]
Ok, as I've said before, if @LoneDev6 decide to make this change and use ``#startsWith()`` I will apply it to Velocity ASAP.

I'm agree with your idea, thanks from me.

**Comment by LoneDev6** [comment]
> And yes that is an issue, but not if you use .startsWith as I'm currently doing in my test fork

It's a smart idea and the only solution.
I don't think it has any downside as soon as you first make sure that the string contains `#`.

**Comment by Jake-Moore** [comment]
Why do you need to split? Like I said I have a test jar running and I explained how each scenario works above, you shouldn’t have to split anything or remove any part of the url.

**Comment by YoSoyVillaa** [comment]
I have a question if we implement the ``#startsWith()`` method to _fix_ this issue. If the player from the main server (server which contains the hash in the url), goes to the second server (which doesn't have any hash), all works; ok, but when he tries to come back to the main server (which has the hash in the url), it will fail because if I use ``#startsWith()`` it will make something like this: 

```java
public boolean checkURL(String oldURL, String newURL) {
    return newURL.startsWith(oldURL);
}

String cachedURL = "https://localhost:8234/pack.zip" // Doesn't contain any hash because his last server was the second
String newURL = "https://localhost:8234/pack.zip#G5LY50XBX648E73OWUP4" // Now it has a hash because the main server has it


// If I do this, it will be false because cachedURL does not start with "https://localhost:8234/pack.zipG5LY50XBX648E73OWUP4"
boolean samePack = checkURL(cachedURL, newURL); 
```

I don't know if you understand me.

Maybe splitting the URL as @LoneDev6 said, could fix the problem because the part before the ``#`` is the same.

**Comment by Jake-Moore** [comment]
It won't.
Because "working" when he goes to the second server means it won't update his pack.
Returning to the main server will show the same pack the main server sent first.

Join Server1: sends and receives "https://localhost:8234/pack.zip#G5LY50XBX648E73OWUP4"
Join Server2: tries to send "https://localhost:8234/pack.zip" but is blocked because startsWith determines it's the same pack
Join Server1: your pack is still "https://localhost:8234/pack.zip#G5LY50XBX648E73OWUP4" since Server2's packet was cancelled

It works.

**Comment by YoSoyVillaa** [comment]
That's true, sorry, my bad

**Comment by LoneDev6** [comment]
I guess I have to apply this patch also to Bungeecord.
Well I think it's time to merge the two logics.
I'll do it in by myself the next hours.

**Comment by LoneDev6** [comment]
New logic:
- player joins `server_1`
- respack gets applied correctly
- player travels to `server_2`
- respack doesn't get re-applied because the player already has it
- player travels back to `server_1`
- respack doesn't get re-applied because the player already has it
- player runs `/iazip` on `server_1` (which is the main server with ItemAdder and self hosting enabled)
- respack gets applied to the player since it's a new pack
- player travels to `server_2`
- respack doesn't get re-applied because the player already has it


Tested and working fine on:
`Waterfall version git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510`
`Paper version git-Paper-372 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 214a8c5)`

Please test this jar on Bungeecord (tested) and Velocity (not tested) and let me know.
https://github.com/LoneDev6/BungeePackFix/releases/tag/1.1.0-pre-1

DO NOT FORGET TO SET `main_spigot_server_name` in `config.yml`.

**Comment by Jake-Moore** [comment]
![image](https://user-images.githubusercontent.com/38172916/212429065-9539aa7e-e38c-4cd4-ad10-adbedfac903a.png)

When running /iazip

**Comment by Jake-Moore** [comment]
Velocity doesn't have a config.yml
Only the config.toml

**Comment by Jake-Moore** [comment]
One thing to note, the velocity config will not add main_spigot_server_name when you update the plugin.
The new default is not added.

**Comment by Jake-Moore** [comment]
![image](https://user-images.githubusercontent.com/38172916/212430251-19f86a8c-ccf0-41b3-a0d1-2228db8e3268.png)

iazip doesn't update.
I'm not entirely sure why you did a complete rewrite of the logic
Literally changing it to .startsWith fixed it for me, that's all it took.

**Comment by Jake-Moore** [comment]
```java
package dev.lone.bungeepackfix.velocity.listeners;

import com.velocitypowered.api.event.PostOrder;
import com.velocitypowered.api.event.ResultedEvent;
import com.velocitypowered.api.event.Subscribe;
import com.velocitypowered.api.event.player.ServerResourcePackSendEvent;
import com.velocitypowered.api.proxy.player.ResourcePackInfo;
import dev.lone.bungeepackfix.velocity.BungeePackFixVelocity;
import net.kyori.adventure.text.minimessage.MiniMessage;

import java.util.Arrays;
import java.util.Objects;

public class ServerResourcePackSendListener {

    private final BungeePackFixVelocity plugin;
    private static final MiniMessage miniMessage = MiniMessage.miniMessage();

    public ServerResourcePackSendListener(BungeePackFixVelocity plugin) {
        this.plugin = plugin;
    }

    @Subscribe(order = PostOrder.FIRST)
    public void onServerResourcePackSend(ServerResourcePackSendEvent event) {
        if (plugin.getConfig().getLog().isDebug())
            plugin.getLogger().warn(
                    "ServerResourcePackSendEvent: " +
                            event.getServerConnection().getPlayer().getUsername());

        if (event.getServerConnection().getPlayer().getAppliedResourcePack() == null) {
            event.setResult(ResultedEvent.GenericResult.allowed());
            if (plugin.getConfig().getLog().isSentRespack())
                plugin.getLogger().warn(
                        "Sending ResourcePack: " +
                                event.getServerConnection().getPlayer().getUsername());
            return;
        }

        ResourcePackInfo playerPack = event.getServerConnection().getPlayer().getAppliedResourcePack();
        ResourcePackInfo serverPack = event.getProvidedResourcePack();

        //Notice .startsWith here, and Arrays.equals (was Objects.equals before)
        if (playerPack == serverPack || ((playerPack.getUrl().startsWith(serverPack.getUrl())) &&
                (!plugin.getConfig().getEqualPackAttributes().isHash() || Arrays.equals(playerPack.getHash(), serverPack.getHash())) &&
                (!plugin.getConfig().getEqualPackAttributes().isForced() || playerPack.getShouldForce() == serverPack.getShouldForce()) &&
                (!plugin.getConfig().getEqualPackAttributes().isPromptMessage() || Objects.equals(playerPack.getPrompt(), serverPack.getPrompt())))) {

            event.setResult(ResultedEvent.GenericResult.denied());
            if (plugin.getConfig().getMessages().isEnabled())
                event.getServerConnection().getPlayer().sendMessage(miniMessage.deserialize(plugin.getConfig().getMessages().getMessage()));
            if (plugin.getConfig().getLog().isIgnoreRespack())
                plugin.getLogger().warn(
                        "Ignoring ResourcePack: " +
                                event.getServerConnection().getPlayer().getUsername());
            return;
        }

        if (plugin.getConfig().getLog().isSentRespack())
            plugin.getLogger().warn(
                    "Sending ResourcePack: " +
                            event.getServerConnection().getPlayer().getUsername());
    }
}

```

![image](https://user-images.githubusercontent.com/38172916/212430666-b0a193d3-fdb7-420b-b226-8f4f183e1fbc.png)

**Comment by Jake-Moore** [comment]
This is my modified version that works flawlessly, it really just comes down to replace equals with startsWith

Up to you if you want to debug your version or just go with this, it works.

**Comment by Jake-Moore** [comment]
@LoneDev6 please refer to the comment above for the solution I have been recommending since I made this thread.

**Comment by YoSoyVillaa** [comment]
> One thing to note, the velocity config will not add main_spigot_server_name when you update the plugin. The new default is not added.
> 
> ![image](https://user-images.githubusercontent.com/38172916/212430251-19f86a8c-ccf0-41b3-a0d1-2228db8e3268.png)
> 
> iazip doesn't update. I'm not entirely sure why you did a complete rewrite of the logic Literally changing it to .startsWith fixed it for me, that's all it took.

I'm agree with you, beacause if you have more than one "multiserver" in your network, 2 or more different resource packs shared with different subservers, url port should be different and it would update your pack, but idk why he did it, from my point of view, no reason to do it.

**Comment by YoSoyVillaa** [comment]
> ```java
> package dev.lone.bungeepackfix.velocity.listeners;
> 
> import com.velocitypowered.api.event.PostOrder;
> import com.velocitypowered.api.event.ResultedEvent;
> import com.velocitypowered.api.event.Subscribe;
> import com.velocitypowered.api.event.player.ServerResourcePackSendEvent;
> import com.velocitypowered.api.proxy.player.ResourcePackInfo;
> import dev.lone.bungeepackfix.velocity.BungeePackFixVelocity;
> import net.kyori.adventure.text.minimessage.MiniMessage;
> 
> import java.util.Arrays;
> import java.util.Objects;
> 
> public class ServerResourcePackSendListener {
> 
>     private final BungeePackFixVelocity plugin;
>     private static final MiniMessage miniMessage = MiniMessage.miniMessage();
> 
>     public ServerResourcePackSendListener(BungeePackFixVelocity plugin) {
>         this.plugin = plugin;
>     }
> 
>     @Subscribe(order = PostOrder.FIRST)
>     public void onServerResourcePackSend(ServerResourcePackSendEvent event) {
>         if (plugin.getConfig().getLog().isDebug())
>             plugin.getLogger().warn(
>                     "ServerResourcePackSendEvent: " +
>                             event.getServerConnection().getPlayer().getUsername());
> 
>         if (event.getServerConnection().getPlayer().getAppliedResourcePack() == null) {
>             event.setResult(ResultedEvent.GenericResult.allowed());
>             if (plugin.getConfig().getLog().isSentRespack())
>                 plugin.getLogger().warn(
>                         "Sending ResourcePack: " +
>                                 event.getServerConnection().getPlayer().getUsername());
>             return;
>         }
> 
>         ResourcePackInfo playerPack = event.getServerConnection().getPlayer().getAppliedResourcePack();
>         ResourcePackInfo serverPack = event.getProvidedResourcePack();
> 
>         //Notice .startsWith here, and Arrays.equals (was Objects.equals before)
>         if (playerPack == serverPack || ((playerPack.getUrl().startsWith(serverPack.getUrl())) &&
>                 (!plugin.getConfig().getEqualPackAttributes().isHash() || Arrays.equals(playerPack.getHash(), serverPack.getHash())) &&
>                 (!plugin.getConfig().getEqualPackAttributes().isForced() || playerPack.getShouldForce() == serverPack.getShouldForce()) &&
>                 (!plugin.getConfig().getEqualPackAttributes().isPromptMessage() || Objects.equals(playerPack.getPrompt(), serverPack.getPrompt())))) {
> 
>             event.setResult(ResultedEvent.GenericResult.denied());
>             if (plugin.getConfig().getMessages().isEnabled())
>                 event.getServerConnection().getPlayer().sendMessage(miniMessage.deserialize(plugin.getConfig().getMessages().getMessage()));
>             if (plugin.getConfig().getLog().isIgnoreRespack())
>                 plugin.getLogger().warn(
>                         "Ignoring ResourcePack: " +
>                                 event.getServerConnection().getPlayer().getUsername());
>             return;
>         }
> 
>         if (plugin.getConfig().getLog().isSentRespack())
>             plugin.getLogger().warn(
>                     "Sending ResourcePack: " +
>                             event.getServerConnection().getPlayer().getUsername());
>     }
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/38172916/212430666-b0a193d3-fdb7-420b-b226-8f4f183e1fbc.png)

Is as simple as do this and finish with this, no new config options or things like that.

**Comment by YoSoyVillaa** [comment]
> One thing to note, the velocity config will not add main_spigot_server_name when you update the plugin. The new default is not added.
> 
> ![image](https://user-images.githubusercontent.com/38172916/212430251-19f86a8c-ccf0-41b3-a0d1-2228db8e3268.png)
> 
> iazip doesn't update. I'm not entirely sure why you did a complete rewrite of the logic Literally changing it to .startsWith fixed it for me, that's all it took.

But not only rewrite of the plugin's logic, fully rewrite of classes that works as expected, like the Config class, a complete recode, also absolutely unnecesary.

**Comment by LoneDev6** [comment]
> I'm not entirely sure why you did a complete rewrite of the logic

I didn't rewrite the plugin, I now handle the hashtag  in the URL correctly, before it wasn't even handled in the plugin logic and results were unreliable.

> Literally changing it to .startsWith fixed it for me, that's all it took.

It's not a clean solution.

Anyway the plugin was tested multiple times on different servers running Bungeecord and works just fine.
It's not clear to me what is not working for you.

Today I'll setup a velocity proxy and test the plugin. 

> main_spigot_server_name 

This option was added to allow the proxy plugin to identify when ItemsAdder resourcepack URL gets updated and know if the cached pack URL is not valid anymore and players need to get their pack reinstalled.
"startsWith()" is not reliable.

**Comment by YoSoyVillaa** [comment]
> This option was added to allow the proxy plugin to identify when ItemsAdder resourcepack URL gets updated and know if the cached pack URL is not valid anymore and players need to get their pack reinstalled.
"startsWith()" is not reliable.

This doesn't make a lot of sense, because if player enter from a subserver with the same host & port from the last server, he ignores the resource pack, but his cached resource pack url stills containing the resource pack hash and the host & port from the main server, so if he switch server with a server that has diferent port, for example, or different resource hash, the proxy will update his texture pack.

A different thing is when from the main server you run /iazip, I don't know if the main servers tells the subservers to update their players resource packs, in that case, things should change, but I don't know the subserver's behaviour when the main server runs /iazip.

> You clearly didn't understand how the cache is used. I suggest you to re-read it. It's used to keep track of the main server resourcepack and identify when you run /iazip to regenerate the resourcepack.

Not really, because if you cancel the resource pack update, you cached resourcepack url stills containing the hash, so you don't have to make a cache containing the cached URLs that are already in the Player object.

**Comment by YoSoyVillaa** [comment]
> main_spigot_server_name 

If you have more than 1 main server this could not be a solutions, if I have to survival modes in a multiserver way, the overworld, nether and end of both gamemodes are in different servers, so there are 2 different resource packs, with that option yo assume that all networks will only have 1 resourcepack

**Comment by LoneDev6** [comment]
This is meant to be used by networks who follow the usual ItemsAdder logic:
Multiple servers with ItemsAdder installed and with the same configurations/assets.
Every server has the external host link set to the main server resourcepack URL.

If you have a different setup this is not ideal because would mean that your players would need to get their resourcepack refreshed when they join some other ItemsAdder servers and it's not something ideal, it breaks the whole purpose of the plugin.
https://itemsadder.devs.beer/faq/single-resourcepack-bungeecord

The "startsWith" logic is flawed and I already explained why in my previous message:
https://github.com/LoneDev6/BungeePackFix/issues/22#issuecomment-1378529712

**Comment by LoneDev6** [comment]
# My test on Bungeecord

## server_1

Spigot server
```yml
    self-host:
      enabled: true
      server-ip: 127.0.0.1
      pack-port: 8163
```

## server_2

Spigot server
```yml
    external-host:
      enabled: true
      url: http://127.0.0.1:8163/generated.zip
```

## proxy

Bungeecord (Waterfall) server

```yml
equal_pack_attributes:
  hash: true
  forced: true
  prompt_message: true
ignore_hash_in_url: true
main_spigot_server_name: server_1
ignored_servers:
  - ignored_1
  - ignored_2
```

Everything works just fine as described in my previous post.
https://github.com/LoneDev6/BungeePackFix/issues/22#issuecomment-1382138429


https://user-images.githubusercontent.com/27242001/212655334-e42b1107-f302-46a0-bb86-d95523a40134.mp4


-------

I'm now installing velocity to make a test also on it.

**Comment by Jake-Moore** [comment]
Im glad this project is open source, and I'm glad it looks like everything works 

I will continue to use my forked version which can expand for our specific network needs (like having server main servers)

I believe this issue can be resolved.

**Comment by LoneDev6** [comment]
I did a lot of tests and works fine for me.
I can safely say that the the plugin is now stable and works good on servers which use the # hash method (ItemsAdder self hosting and I think some other plugins).
